language: node_js
node_js: 8
dist: trusty
sudo: required
node_js: stable
install:
- npm install -g bower pulp purescript
- pulp --version
- npm install
- bower install --production
script:
- pulp build
